const epTitles = [
    "Piloto",
    "The Cat's in the Bag",
    "And the Bag's in the River",
    "Cancer Man",
    "Gray Matter",
    "Crazy Handful of Nothin'",
    "A No-Rough-Stuff-Type Deal",
    "Seven Thirty-Seven",
    "Grilled",
    "Bit by a Dead Bee",
    "Down",
    "Breakage",
    "Peekaboo",
    "Negro y Azul",
    "Better Call Saul",
    "4 Days Out",
    "Over",
    "Chega!",
    "Cavalo sem nome",
    "Eu transei com Ted",
    "Sinal verde",
    "Mas",
    "Ao pôr do sol",
    "Um minuto",
    "Eu vejo você",
    "Kafkiano",
    "A mosca",
    "Estilete",
    "38 cano curto",
    "Casa em exposição",
    "Frases curtas",
    "Espingarda",
    "Encurralado",
    "Cachorro problemático",
    "Hermanos",
    "Escuta",
    "Saúde",
    "Viva livre ou morra",
    "Madrigal",
    "Hazard Pay",
    "Cinquenta e um",
    "Evoluir",
    "Aquisição",
    "Diga meu nome",
    "Planando sobre tudo",
    "Dinheiro sujo de sangue",
    "Enterrado"
]

const epDurations = [
    "58min",
    "48min",
    "48min",
    "48min",
    "48min",
    "48min",
    "47min",
    "47min",
    "48min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "46min",
    "46min",
    "45min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min",
    "43min",
    "47min",
    "47min",
    "47min",
    "48min",
    "47min",
    "47min",
    "47min",
    "47min",
    "47min"
]

const epDescriptions = [
    "Um professor de química do ensino médio começa a vender drogas para sustentar sua família.",
    "O saldo da primeira transação fracassada de Walt e Jesse é de dois cadáveres e sua desova. Skyler suspeita que seu marido esteja tramando algo.",
    "Enquanto Walt limpa a bagunça que foi deixada após a primeira venda de drogas, ele pensa em contar a Skyler o segredo sobre a sua doença.",
    "Forçado a revelar a verdade sobre sua doença, Walt enfrenta o dilema de pagar pelos caros tratamentos de câncer.",
    "Skyler organiza uma intervenção para persuadir Walt a aceitar a generosa oferta de seu antigo parceiro de pesquisa de pagar pelo seu tratamento de câncer.",
    "Conforme os efeitos colaterais e os custos do seu tratamento aumentam rapidamente, Walt exige que Jesse encontre um grande comprador para suas drogas, deixando Jesse encrencado com um perigoso ex-presidiário.",
    "Após Jesse escapar da morte, Walt concorda em produzir mais drogas para Tuco, enquanto Skyler suspeita que sua irmã roubou um presente de chá de bebê.",
    "Enquanto planejam sua última grande venda, Walt e Jesse temem que Tuco esteja pensando em matá-los assim que a entrega for feita.",
    "Como a caçada humana dos federais a Tuco continua, Skyler coloca Hank atrás de Walt.",
    "Como Hank chega muito perto de descobrir seu negócio de drogas, Walt monta um plano para despistá-lo",
    "Ao passo que Walt vai vencendo o crescente abismo entre ele e Skyler, Jesse fica sem um lugar para morar depois que seus pais o despejam de casa.",
    "Hank tenta se recompor depois do encontro com Tuco. Jesse contrata mais gente para aumentar a oferta do produto.",
    "Enquanto Jesse persegue os viciados que roubaram o estoque de drogas de Skinny Pete, Walt inventa uma história para explicar como ele paga o seu tratamento contra o câncer.",
    "Enquanto a reputação de Jesse como um grande traficante de drogas faz com que Walt aumente sua produção, a caminhada de Hank o DEA de El Paso o deixa inquieto.",
    "A prisão de Badger força Walt e Jesse a se associarem a um advogado sombrio.",
    "Preocupado por não ter muito tempo de vida, Walt espera sustentar sua família inscrevendo Jesse em uma sessão de preparação de metanfetamina para uma maratona no deserto.",
    "Depois de receber boas notícias sobre o seu tratamento contra o câncer, Walt droga Hank antes de colocar as coisas em ordem em casa.",
    "Após o desastre de avião de Albuquerque, Skyler força Walt a se mudar, enquanto a estadia de Jesse na reabilitação o ajuda a entender seu papel na colisão fatal.",
    "Quando sabe que Skyler está determinada a pedir o divórcio, Walt, inconsciente, cai na mira de um par de traficantes mexicanos com sede de vingança.",
    "Walt acha que Skyler está blefando e volta para casa sem consentimento. Jesse quer voltar ao tráfico. Um cartel mexicano espera a chance de vingar a morte de um dos seus.",
    "O caso de Skyler com seu chefe cria caos em seu complicado casamento. Um novo lote de metanfetamina coloca Jesse de volta no negócio e Walt também acaba se envolvendo.",
    "Skyler reconsidera suas objeções a que ele volte para casa. Walt estuda uma oferta para voltar ao tráfico. A obsessão de Hank com Heisenberg traz problemas para Jesse.",
    "Enquanto Walt volta a trabalhar no laboratório de metanfetamina de Gus, a descoberta do antigo RV força ele e Jesse a agirem rápido para não serem presos por Hank.",
    "Chateado com o fim do caso pela destruição do laboratório móvel, Hank arrisca sua carreira atacando Jesse; preocupado, Walt lhe propõe recomeçar em seu novo laboratório.",
    "Hank se apega à vida depois que o cartel de drogas tenta matá-lo. Walt tenta ficar longe de problemas ao associar-se a Jesse quando percebe que também pode ser alvo.",
    "Quando ele e Walt retomam a produção, Jesse procura aumentar sua fatia, enquanto Marie tem atrito com a seguradora por causa das chances de recuperação de Hank .",
    "Uma longa noite no laboratório faz Walt e Jesse discutirem sobre uma mosca.",
    "Depois de um momento tenso na terceira temporada em que Walt e Jesse batalharam por suas vidas, a dupla aguarda para ver os próximos passos de Gus.",
    "Enquanto Walt prepara sua defesa contra Gus, Jesse lida com a pressão ao renovar sua amizade com Badger e Skinny Pete.",
    "Walt se preocupa com a interferência de Gus e a fragilidade mental de Jesse. Skyler aumenta a pressão para conseguir o que deseja.",
    "Skyler cria uma história elaborada para explicar as finanças da família White, e Walt descobre que Hank começou uma nova investigação.",
    "Jesse acompanha Mike em um arriscado passeio para fazer coletas, deixando Walt preocupado que seu parceiro poderá ser morto.",
    "Skyler adota uma abordagem indiferente ao suspeitar que Walt não diz a verdade. Enquanto isso, Jesse prova seu valor para Mike e Gus.",
    "Obrigado a devolver o carro que comprou para o filho, Walt contra-ataca deixando Skyler em maus lençóis com o novo esquema de lavagem de dinheiro.",
    "Quando Hank descobre provas de que Gus é o barão da metanfetamina de Albuquerque, Walt acha que ele e Jesse serão mortos enquanto protegem o chefe.",
    "Walt tenta subverter a investigação de Hank no mercado de metanfetamina de Albuquerque, e um perigoso aviso força Gus a considerar um negócio com o cartel mexicano.",
    "Enquanto Walt ainda se recupera da briga, Gus leva Jesse ao México para concretizar o negócio com o cartel mexicano.",
    "Walter vai visitar a família, que ainda está sob proteção policial, enquanto lida com as consequências da explosão na Casa Tranquila.",
    "Walt e Jesse decidem procurar um novo parceiro para a próxima empreitada e a polícia investiga várias pistas na tentativa de descobrir algo.",
    "Walter volta a morar em casa, deixando Skyler desesperada. Walter, Mike, Jesse e Sal procuram por um novo local para “cozinhar”.",
    "Lydia entrega o próprio chefe para a polícia e Mike oferece um substituto: Jesse. Walter e Skyler discutem sobre a segurança da família.",
    "Mike e Lydia estudam uma maneira de transportar a metilamina para a nova operação e Walt e Jesse tentam bolar um plano que não estrague seu disfarce.",
    "Walt, Mike e Jesse lidam com as consequências do roubo da metilamina. Mike e Jesse querem desistir, mas Walt está decidido a construir seu império.",
    "Walter tenta fazer um acordo com Declan. Hank recebe ordens para deixar Mike em paz e passa a investigar o advogado que paga os homens de Mike.",
    "Walt se encontra com Lydia para conseguir o nome dos comparsas de Mike na cadeia. Skyler tenta convencer Walt a deixar de produzir metanfetamina.",
    "Walt e Jesse tentam se ajustar à vida longe do tráfico e Hank descobre uma pista perturbadora.",
    "Enquanto o passado de Skyler vem à tona, Walt tenta encobrir seus próprios rastros e Jesse tenta lidar com o sentimento de culpa."
]

const epNumbers = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10"
]

const epThumbs = [
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABWop0VY1PP3pHXykX9N4L4lWg28EdiyJpgqz_vjeHTsyxc2uqh2hNJNmcwC1UGwI_fZSOVRYT0mvCnpBr7w3Sadjlr_kOTqs2hkJ5Il7khXjsldR1hn5F0IS.webp?r=910",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABXB0INSyQJ2lTnVCVsTgK4Dkzwp-46CAhDEvm4fZG5RXeRXZZ7wpOGe6Up4z4T-ENUqL6s5l2HarORp5CsAvyQVKg_AGG3zNpvCh5XQ4CnaokHM80rt1Doiw.webp?r=910",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABcQgVcxBUyF9OW6ZT9F9zFTGbmE_d38f2onzM-ILw4T-8DeV-ODM7wOlPcd1jopi3hlJW_9GzEw099fJgw2xboJ8Ze4h_8whiHo0zGwjk84QMVeQQ3XwKYQm.webp?r=ea1",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABQ5J0CbEl37lE5mWS-E-c-m-bCFrYkhLx3p823qABn3QhvKde8uQBVL8gO2hGMlLBiC_g9RUBWnSsNJ2B9vYt1c3tk9dvpGXJAw6dES9j0yb5iQoZQna5cZF.webp?r=f8d",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABf2qP9Iuyte--yoEOAp7PpHyB7FnDmZSt-D6q2Dr9Bqus5y3UDL6HbENsMTWktPFzU9Xz-nx4HwPX6PyhQP4nh0oJ55lRAYBEJM7nkLZ9BYrutIZEOdpmd_-.webp?r=2cc",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABbwxgJD3bOraGwZWNDpDYIf1QahNDNudwL4FFrHnsd5fxx_vCVUhIFjHXudq8QUZJnK5Lq7TZzoWNiEmfZuBkECHr1arl4Q8ffPalqpujGJS74QuC_CoMPjR.webp?r=e4a",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABfVbyQIMHpo3x8uaZPeOw7isY0LNQP5MtrMm3NaJMIqUH1iju-PnwiC8iwg6Ptf4xcOyXZwKDLeUBgOhNUnjN5uhTY0zaz7IAscF-CNXtQ2Izx8a9SYx3yTn.webp?r=0b0",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABdQPsviieJ5ZN_q5JxGTyew3rd3eqS-Z5ClMpVLPCli9DWMx8mvaF9uwCiJEwAihr5ixOrgxgMEnoEi-QEzmWi7PXwnsZZyjMmmAgpy7kL69gSTEJ6ZnZQzZ.webp?r=4c4",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABR9H_KY0L6pSBPgMPhs5KEgJbq32P80wB_EkpNTycB_xLvGABHtmgkoD4tnWnScwhNWdnGYtTMPWAwXKOeIMDbcwEeFO4P0gwPA_-1mEj83e6CcGeIni2MTK.webp?r=829",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABaVg_9MXnHfLZvGn6vtFnKGpaZsjpv8C7g_Cxca4yCQzQTQFXD8IN26GxXMIbxpjlR4FIOTINsPlygHfJoeIaI2CeQqVmbjTO8FsMUS8-wAW9vi4s5mT67_6.webp?r=4e9",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABYBLFlt-9UHp6wYlCrkgbz-nMogbzR-rMe0xYxYvl7THiHjwsz8RHFSeh7pSXJAwYJc8elThNItH_HnG_fmoEE2jRTa7qG0uLnjCg-Cw59IJ_LO90EiD_lnA.webp?r=5c3",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZmsU4xJ0yZwDsirQ0t8sIrkHABkxIMdcasc0Z4pHmQp_nIqRer6gJwpxbN-kON7D2dI1qXycnQf23ExDLTCe5LiUBwy1QPoXkSkQGDc98ojGyzLIhgW4S6l.webp?r=6e5",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABWosZIx9hU5KgMGuV4lJNGwfF9OpOJsGiegFMs9b_KjN4Mdf-vWlNVK8B5Q7cKCW2sDDKIRronigzE5MmGL5wiGLdGEtv_-5bpkMxLJxB33KtoVlCFVicBKW.webp?r=34c",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABdo7MjZMvCxWjgykJTjDZ7RNzXqeu5c8r5cBzQNw_D37ozPV-kp1M-lOUoNvzq18FaGcEZnRhE32gy2xNtp6nfg3m-RGwJdDdlNu2tUxBHXA0MKOI42k1LIZ.webp?r=3a0",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRZC_co3vr4xnKnoHZZZOmF8fJPn06_pdHWrSdP7naF7cRg5vwTtBQrNH_EUfo8HtDCgsRVMjDtWL1S1cJ5eXXhEYPUfCQSmIDJRTfR2I0myG3Zx8lkiDd8-.webp?r=922",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZ62nadHPlQtYaQUvjh0BgyxIYJUIBoH4M-DDlN9UeLAcyvj6pMrSPyU92_lo0a2E4F-PPCZmS7w_pJ37gQa4dLgx2n1h_j-vSWQYRkt4z6U1Y8McTTHIh6i.webp?r=4f1",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABQW8moVtvqBtbQni3lgv1cRgO3avQqNY0bzV78FmL95kiEGx-IYn_4JAwIXHLeJUeycWnXgf6EeuI2iaJeiLJs1_RaJaXeatbUBjYcZawRPomUCuttVCzMIs.webp?r=c3b",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABfegvTyfo06j11xIBWoICkxGZGpe4daQFs0EYrz5Fqcmj-4LgFYcQ2N8mdCFF7CyQ691UI2ozuh2zlAhdECGW4kzcJJLMw0cX5Qa4_56yZTuraOfa8Em_0Pm.webp?r=46a",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABUJz7sGl_zbGfLQ3zIvJ8CFPmHUbwahX63m4sfVYnds5S7m0-_GhccRWaedHLNrcA4o2FyQIztOHBCLfPi59FIyjS3GN1Qicfk0YKkJZ7q9bHjlXSdyfgl5m.webp?r=bbc",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABV4PSg8lKjuiD8JMDtDmR19oIX0WPXJKXW2BKcNSAomYReYtvDD0wopAQZtv4jMC4xTqNRu_B8ydVqVLx5Xjc2KOmCgdl0_xQEcDM1CN-vWdBRBFImKA29NZ.webp?r=68a",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABZwF2sHqJegz7ST8EwSgB5KzTmlzPkYHeHisEI_5JwfDaL3HZR_1k3wuAA1lVReGC-aGiYVlLwuRYvKuNl7uajW1PiJBgHZS8FMcUFwl7pn1KY_0wBM0tUcJ.webp?r=87b",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABbMBOIgH-USciZPqlRhpx6huWZ7qrrCBq5nmQhvmrvssr_GQyP9QlBVFGomEidqyd3IjnfNEuZlGwUN_pMJqaAG-9wh06YHNDL7keB8Rh-HYJi9ecp6l5-ar.webp?r=c68",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABVV6AvMCHmijL4O_48Q2HN4v5DOk6DR66Ao3GStDr0nopKun_SV0iNq7PrHs80-_6Ze72rnMPdDBASFC5PugvZXJqPdlRpvLTYRxyKzywAlEXmgHHJd-45hI.webp?r=0b2",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABeG0FSmfsP6PKdqsCMMgKSmrDdhJKp_kHckNIwMr0ABJiLLXkGfuw8H2fG_SBvnCLA4Si5XL9QjgwDtikGiyViJEuSlYUi1RjQ25W1IXHlez43ZtBUKvyUP_.webp?r=02b",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABdsmDuqSHCA7uX6TxofdH8OYRyHri4ZJV2YmCVampP0av8uc2URmjyQ_oXXmbMrXbpd29NPmRhLZ1HJ4U6ir4Qg_LS2Vpf2lJfcIrBiveHCUUVcmowvQqtRu.webp?r=c44",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRVbVq4tBYdmvocIm8QWOfN-l7IHEW1yQojvdMqHaIKGC2bsG4nhqPbYXuEVtcOof9tzXs82kTMJMkJvo9ydyqnKFET0Kh8nlJjKasYUJwMBwgZaxkILO8jV.webp?r=654",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABa7rwQ2br7L4DHsyc8lgN8piz5KrVE0faCOgI2KJQXMlG71t9ix8mdeTLH1Fqm6bRBKy7d_Oj1CT9KcmLk_aRpu1Kvg_HKPr8eEFR3TcZIjbhpc8EOO2QPZB.webp?r=56c",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABQm91GgmEgJcT5JpSmMUXsJlEehFYrm42cEWvi2d-wyLjianzkICnuZ4PvNruouhTiF5QD_J_WKiSVg01pKYQ8VHzwTHk-iLSKrCF0lQdGHYBKBTCVgn7itp.webp?r=d4d",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABa1RkXzsdBJQ_rThVfgWVp54jfTIUcvzfiw3EJK2LlZpddRoLdQEqP5eK-fJXxyYbz3YyYthF9VtmPswLfF-VgbniT8b4SHH7Ma78ckAuKZTzOiBtWnD_GDr.webp?r=6d1",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABfjODOFZcfqa0NeKQyGIF1nmP7zAO35MpiaGmo1WAtyM8hPvvGFPxYQHmi9DMqNpE7unMIkYYhcf1wew46Y0uJ71NSRsC80M_qSccqgWadwSAKnTox-1XiIC.webp?r=ba4",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABX2z17Cv3GRFsOYehJBAM_3mFz0AY-kcumJButvMmQeV1zf3gf-i4p2_gaxgO-eW_MWVRwAwr2Ypb96xzrd7SijIIPwZv8kCvtYxR57oWFzy0CTtXTLwCZfa.webp?r=bad",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABUWJ4FJQ6cHCxYgD5FNrtsjk-6JMeVas84LSh242mE7uFG6shhteIfkW-oXmkm5HqzI8DzL6beM0O1sqgYqjYgx5Ze8dKWqlodNNFxmI8bpRVzVzxwO1vh90.webp?r=1d4",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABaB0yWHrg9NHMhyAF0H2w1wuvyog8biN0LI5lor99xdtBStBoKspdLmctlS1uWE-l1pN5IGIl_1jr_sMFmn9Ph0c4-P79tDU6nRPGfGhjaZakZ_04EKYezd0.webp?r=1b8",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABVdMjDDKCIBQQehVg_EIQCDRQtNuH3Zoq00Ag8gXR5cqoDrCreMnAIJX58FXeUPS-bc357iSvgJWdw9RbfDY1TAJO1737pbeXBULeqFbpThz62QQ8TBL_xAi.webp?r=156",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABbEKkEnQHZgL09_VnHllq9A164RBxbkDyfXpymEWSnLnxKfnJTaW-m4jwrd1JlX9t4XlNd1scNvgP0qilwkA7pph1WEca68uBMTv_e5pmUZjMYVvurDhJOEy.webp?r=bdc",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRIN4qloq8hGfgynnYXHTW6tielzqchB1gdnr5jKwoh8HFF4XuROoX-GYLSNytWi3FU26HfXHX-3F2XHiP1RVcJmdEBOGpLfROzUPhCxhzpnyUj7HQJBRzt7.webp?r=023",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABTCnx70h297X6RanoqVsHItIdhLnA5Ey2U-juQHz7a7PhF0LUx_0X6t9j5VL7iE-LQ2CZLZbffw0xXjM_FvajfEpJaBWjP5foSTMok0lqli04zcJa0_hUuT8.webp?r=f28",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABcjrrJmhZ2hbTu3VX-akYrmbOpbEE8uAYgofJIbhaHiZLaWDn6DuVSvRh4x3LwhXUK7PfkcZ-sqZAvEN5aVpML5nfzEDUwVgIIF6d5F4wV5UXOM6JaxGjWfq.webp?r=428",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABV-WZQi5N5gsgJckEGKAIaDMrI14uXVRLZSMg-vFzXUnqxjW63sdFMcsDDlOFa8JK7vTSr2FUVB_vwdm-U7mhnqkEXYPweKYULEve1J8o5_VFTU7LZ8vH-hC.webp?r=be7",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABfjEnxKC-yTL6KLUKiq-G44odMSfZYyhnF7mwYHjOCweQ_3qXVA5BEavMdWF3fmI2rAU24rXL0VVD56zCYa6TbOA6UXjUO12YPX5m1HZZW8rF_zwlK6FHsfD.webp?r=237",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABdYLEPsPPOe0RCoJ3Gq7eBGfSySbIixeO4UmdQbYhgJmntHJaEvRsKchbkxm-J4h2QY22SlMfQKg-CVBNnaJ5n60Jx6yq3FZo6ag2ExGktYE-WZrsFN8-spW.webp?r=0b5",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABSg-cEvChkYTwEtSvCrddGfawg0KqDxzBJN7IqZG2aEAE-wIYraNimpwHz8-sGWWFfPhSoykzs0VBky27zqkthhza9_TXVS01t-ma5yU55p65mdC-7mvXbLK.webp?r=dd9",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABd_WyhQt5HI3uXP_p0UV9tB-kBLHLJ8jYgq34iAqb2ZLC68qHxle_01cpKZRkC3vYaYHFgc9gYTFQ-WmI6djBhUkVfEdheZmdHMulJBz2BcPw0QUsGNpe-eO.webp?r=296",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABVwJNHIiyVvPyBe9T7LwujmHhVlfdExxI4Mc0wqacDn9QenuAfXdSyte7Ti06JfodTYk_vNhm9FhHXjD2JTge5juG1Bmh4nocN5v4-WaxDMiOG170XQy9X12.webp?r=b33",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABQbMZd14FefkUw-0iWuvtMicPNcWLnaifIBDF8WVANZzaao8xcYef-S0JoCSzIZodPM6gdpSFvsWDuEwxM7gmGGSRBEw7R513wueypMhVvgKWzAF67wILKQR.webp?r=18d",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABQ4LOvBZia4TO1W1thjexoEajTyCFJ84kM0uNwGEFEBemFWgJmJl0NwmHmHj4ti-iDh0mlL4a48Bo_nWf-UlPN1wjZhDo-EtnIh6PnQu6AphUvadySRDB_W7.webp?r=917",
    "https://occ-0-1125-1740.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABaxJwhJvwndnMYv7qGJmvjYmlJKlFp96pv9_G3D2inETS5bFWE9dvEQod5nIUa7bthAPJoklv3BZkO6_cVnDHx0cQDP9-33X4Qm1mX46nnuPB-dSVv6qA0Gx.webp?r=30d"
]

let csv = 'epNumber,epTitle,epDescription,epDuration,epThumb\n'
for(let i = 0; i < epTitles.length; i++) {
	csv += `"${epNumbers[i]}","${epTitles[i]}","${epDescriptions[i]}","${epDurations[i]}","${epThumbs[i]}"\n`
}
const fs = require('fs');
fs.writeFileSync('./data/csv.csv', csv);


